version: '3.1'
services:
  rest-api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: user_management_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
      MYSQL_ROOT_PASSWORD: 1111
