version: '3.1'
services:
  db:
    build: .
    restart: always
    environment:
      MYSQL_DATABASE: user_management_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3306:3306"